# -*- coding: utf-8 -*-
"""BeeORWasp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OxcYEeAQNyKoyQBj9W041n-632BmXCJe
"""

!pip install kaggle

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d jerzydziewierz/bee-vs-wasp

from zipfile import ZipFile
dataset = "/content/bee-vs-wasp.zip"
with ZipFile(dataset, 'r') as zip:
  zip.extractall()
  print("Dataset Extracted!!!")

import os
import numpy as np
import cv2
import matplotlib.pyplot as plt
import matplotlib.image as mping
from google.colab.patches import cv2_imshow
from PIL import Image
from sklearn.model_selection import train_test_split

bee_images = os.listdir("/content/kaggle_bee_vs_wasp/bee2")
print(bee_images[0:5])
print(bee_images[-5:])
print(len(bee_images))

wasp_images = os.listdir("/content/kaggle_bee_vs_wasp/wasp2")
print(wasp_images[0:5])
print(wasp_images[-5:])
print(len(wasp_images))

bee_labels =[1]*714
wasp_labels = [0]*2816

print(len(bee_labels))
print(len(wasp_labels))

labels = bee_labels + wasp_labels
print(len(labels))

bee = mping.imread("/content/kaggle_bee_vs_wasp/bee2/NP1034-9r.jpg")
img_plot = plt.imshow(bee)
plt.axis('off')
plt.show()

wasp = mping.imread("/content/kaggle_bee_vs_wasp/wasp2/E00016.jpg")
img_plot = plt.imshow(wasp)
plt.axis('off')
plt.show()

import os


bee_dir = "/content/kaggle_bee_vs_wasp/bee2"
data = []
for img_file in bee_images:
  image = Image.open(os.path.join(bee_dir, img_file))
  image = image.resize((128,128))
  image = image.convert('RGB')
  image = np.array(image)
  data.append(image)
wasp_dir = "/content/kaggle_bee_vs_wasp/wasp2"
for img_file in wasp_images:
  image = Image.open(os.path.join(wasp_dir, img_file))
  image = image.resize((128,128))
  image = image.convert('RGB')
  image = np.array(image)
  data.append(image)

print(len(data))

X = np.array(data)
Y = np.array(labels)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

print(X.shape, X_train.shape, X_test.shape)

X_train_scaled = X_train / 255
X_test_scaled = X_test /255

X_train[0]

X_train_scaled[0]

import tensorflow as tf
from tensorflow import keras

num_of_classes = 2

model = keras.Sequential()

model.add(keras.layers.Conv2D(32, kernel_size=(3,3), activation='relu', input_shape=(128,128,3)))
model.add(keras.layers.MaxPooling2D((2,2)))

model.add(keras.layers.Conv2D(64, kernel_size=(3,3), activation='relu'))
model.add(keras.layers.MaxPooling2D((2,2)))

model.add(keras.layers.Flatten())

model.add(keras.layers.Dense(128, activation='relu'))
model.add(keras.layers.Dropout(0.5))

model.add(keras.layers.Dense(64, activation='relu'))
model.add(keras.layers.Dropout(0.5))

model.add(keras.layers.Dense(num_of_classes, activation='sigmoid'))

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics =['accuracy']
)

history = model.fit(X_train_scaled, Y_train, validation_split=0.1, epochs =10)

loss, accuracy = model.evaluate(X_test_scaled, Y_test)
print("Accuracy score is:", accuracy)

h = history

#plot the loss value
plt.plot(h.history['loss'], label='train loss')
plt.plot(h.history['val_loss'], label='validation loss')
plt.legend()
plt.show()

#plot the accuracy value
plt.plot(h.history['accuracy'], label='train accuracy')
plt.plot(h.history['val_accuracy'], label='validation accuracy')
plt.legend()
plt.show()

input_image_path = input('Path of the image to be predicted: ')

input_image = cv2.imread(input_image_path)

cv2_imshow(input_image)

input_image_resized = cv2.resize(input_image, (128,128))

input_image_scaled = input_image_resized/255

input_image_reshaped = np.reshape(input_image_scaled, [1,128,128,3])

input_prediction = model.predict(input_image_reshaped)

print(input_prediction)


input_pred_label = np.argmax(input_prediction)

print(input_pred_label)


if input_pred_label == 1:

  print('THIS IMAGE IS BEE !!!')

else:

  print('THIS IMAGE IS WASP !!!')

input_image_path = input('Path of the image to be predicted: ')

input_image = cv2.imread(input_image_path)

cv2_imshow(input_image)

input_image_resized = cv2.resize(input_image, (128,128))

input_image_scaled = input_image_resized/255

input_image_reshaped = np.reshape(input_image_scaled, [1,128,128,3])

input_prediction = model.predict(input_image_reshaped)

print(input_prediction)


input_pred_label = np.argmax(input_prediction)

print(input_pred_label)


if input_pred_label == 1:

  print('THIS IMAGE IS BEE !!!')

else:

  print('THIS IMAGE IS WASP !!!')

